version: '2'

services:

  drupal:
    image: drupal
    ports:
      - 8081:80
    volumes:
      - ./drupal-modules:/var/www/html/modules
      - ./drupal-profiles:/var/www/html/profiles
      - ./drupal-themes:/var/www/html/themes
      - ./drupal-sites:/var/www/html/sites

  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./pg-data:/var/lib/postgresql/data
